# Generated by Django 5.0.6 on 2024-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company_alter_job_date_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
