# Generated by Django 5.0.6 on 2024-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_summary_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
